---
title: "컴퓨터, 주식을 배우다"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: i@minje.kr
description: Except where otherwise noted, content on this site is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution 4.0 International license.</a>
baseurl: "/learningstock"
url: http://minjejeon.github.io
github_username: MinjeJeon
markdown: kramdown
