#!/bin/sh
git rm -rf --ignore-unmatch --cached $PWD/_drafts
git rm -rf --ignore-unmatch --cached $PWD/_site
git rm -rf --ignore-unmatch --cached $PWD/python_tools
git rm -rf --ignore-unmatch --cached $PWD/.sass-cache
git rm -rf --ignore-unmatch --cached $PWD/.vscode
git rm -rf --ignore-unmatch --cached $PWD/tools
git rm -rf --ignore-unmatch --cached $PWD/notebooks/drafts